// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjvSiOS31phtVE8Hy5sMVqtRCOJ6p9sNM',
    appId: '1:298668208572:web:bec455be7daf7671fb3bb9',
    messagingSenderId: '298668208572',
    projectId: 'chatlify-89dd3',
    authDomain: 'chatlify-89dd3.firebaseapp.com',
    storageBucket: 'chatlify-89dd3.firebasestorage.app',
    measurementId: 'G-P35Z5R4FJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM6RorHH0mYgjvWrppcRAQFi_eJAGgPU0',
    appId: '1:298668208572:android:d4837f9ccb1cec74fb3bb9',
    messagingSenderId: '298668208572',
    projectId: 'chatlify-89dd3',
    storageBucket: 'chatlify-89dd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeqkCVbGr1dQL799voxmCcwIXjAREw7oU',
    appId: '1:298668208572:ios:ecbc3c7f6ecaa21dfb3bb9',
    messagingSenderId: '298668208572',
    projectId: 'chatlify-89dd3',
    storageBucket: 'chatlify-89dd3.firebasestorage.app',
    iosBundleId: 'com.example.chatlify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeqkCVbGr1dQL799voxmCcwIXjAREw7oU',
    appId: '1:298668208572:ios:ecbc3c7f6ecaa21dfb3bb9',
    messagingSenderId: '298668208572',
    projectId: 'chatlify-89dd3',
    storageBucket: 'chatlify-89dd3.firebasestorage.app',
    iosBundleId: 'com.example.chatlify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjvSiOS31phtVE8Hy5sMVqtRCOJ6p9sNM',
    appId: '1:298668208572:web:369b200d1e440277fb3bb9',
    messagingSenderId: '298668208572',
    projectId: 'chatlify-89dd3',
    authDomain: 'chatlify-89dd3.firebaseapp.com',
    storageBucket: 'chatlify-89dd3.firebasestorage.app',
    measurementId: 'G-VS2HCYCNCL',
  );
}
